### ISSUE TITLE
Install Error While Following Deb Package Install Instructions

### ISSUE THREAD

**Issue by jimbolya0607** [TheHive-Project/TheHiveDocs#36] opened 2018-03-01 21:48 UTC
Received this error when installing from Deb Package. 

Err:11 https://dl.bintray.com/cert-bdf/debian any/main amd64 Packages
  404  Not Found
Ign:12 https://dl.bintray.com/cert-bdf/debian any/main i386 Packages
Ign:13 https://dl.bintray.com/cert-bdf/debian any/main all Packages
Ign:14 https://dl.bintray.com/cert-bdf/debian any/main Translation-en_US
Ign:15 https://dl.bintray.com/cert-bdf/debian any/main Translation-en
Fetched 102 kB in 3s (34.0 kB/s)
Reading package lists... Done
W: The repository 'https://dl.bintray.com/cert-bdf/debian any Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://dl.bintray.com/cert-bdf/debian/dists/any/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jimbolya0607** [comment] 2018-03-01 21:49
Also this:

sudo apt-get install thehive
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package thehive
rinth@Laby-Hive:~$

**Comment by jimbolya0607** [comment] 2018-03-02 02:31
So I did some searching on the web server...

 404  Not Found
Ign:12 https://dl.bintray.com/cert-bdf/debian any/main i386 Packages
Ign:13 https://dl.bintray.com/cert-bdf/debian any/main all Packages
Ign:14 https://dl.bintray.com/cert-bdf/debian any/main Translation-en_US
Ign:15 https://dl.bintray.com/cert-bdf/debian any/main Translation-en
Fetched 204 kB in 5s (40.2 kB/s)
Reading package lists... Done
W: The repository 'https://dl.bintray.com/cert-bdf/debian any Release' does not                                                                                                                                                              have a Release file.
N: Data from such a repository can't be authenticated and is therefore potential                                                                                                                                                             ly dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                                                                                                                                             ils.
E: Failed to fetch https://dl.bintray.com/cert-bdf/debian/dists/any/main/binary-                                                                                                                                                             amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used                                                                                                                                                              instead.

the /dist/any is actually /dist/ny on the web server...

due to this no one is going to actually be able to grab the install package

**Comment by To-om** [comment] 2018-03-02 08:05
I don't understand why Bintray use `ny` distribution as `any` is used in my script to publish packages. Moreover in Bintray interface, `any` is displayed. Scheduling a "metadata calculation" doesn't solve the problem. I continue to investigate

**Comment by To-om** [comment] 2018-03-02 08:30
I've contacted Bintray support.

**Comment by To-om** [comment] 2018-03-02 13:30
Still no news from Bintray. As workaround, you can run:
```
wget https://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
dpkg -i TheHive_3.0.6-1_all.deb
```

**Comment by jimbolya0607** [comment] 2018-03-02 14:42
Modified the line to reflect the correct path

**Comment by jimbolya0607** [comment] 2018-03-02 15:15
@To-om
I've tried that before, and it basically breaks all the other install
instructions from the perspective that you have to modify all the posted
commands to reflect the folder TheHive-3.0.6; which, okay...
However, if you try to simplify it and rename the folder to thehive you
can't due to file name conflicts within the folder.

I just tried to run the install again and it's still not working.  It
worked last night with this command:  echo 'deb
https://dl.bintray.com/cert-bdf/debian ny main' | sudo tee -a
/etc/apt/sources.list.d/thehive-project.list

However if I keep going down the install commands I get this now:

 sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:6 https://dl.bintray.com/cert-bdf/debian ny InRelease
Ign:7 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Hit:8 https://artifacts.elastic.co/packages/5.x/apt stable Release
Get:10 https://dl.bintray.com/cert-bdf/debian ny Release [1,834 B]
Get:11 https://dl.bintray.com/cert-bdf/debian ny Release.gpg [821 B]
Get:12 https://dl.bintray.com/cert-bdf/debian ny/main amd64 Packages [3,408
B]
Get:13 https://dl.bintray.com/cert-bdf/debian ny/main i386 Packages [3,408
B]
Err:13 https://dl.bintray.com/cert-bdf/debian ny/main i386 Packages
  Hash Sum mismatch
Fetched 6,077 B in 1s (3,754 B/s)
Reading package lists... Done
E: Failed to fetch
https://dl.bintray.com/cert-bdf/debian/dists/ny/main/binary-i386/Packages.bz2
Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones
used instead.
Hive:~$ sudo apt-get install thehive
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package thehive
Hive:~$

Jimbo

**Comment by 3c7** [comment] 2018-03-02 16:05
Hello @jimbolya0607, you should be able to continue the installation as mentioned in the documentation after installing the deb-Package manually.

You can add the apt repository and instead of using `apt install thehive` you do the above mentioned workaround (`wget https://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb && dpkg -i TheHive_3.0.6-1.deb`). In case of an error mentioning some dependencies missing, you can run `apt install -f` afterwards. After the TheHive installation you have to continue with installing Elasticsearch.

**Comment by jimbolya0607** [comment] 2018-03-02 16:16
Nils I'll try this, but from my experience the folder name changes that makes setting up services a pain in the butt...
I'll give it a try though.

**Comment by 3c7** [comment] 2018-03-02 16:18
As you install the same deb-Package as you would using the "normal" way, I don't think that any folder name should change.

**Comment by jimbolya0607** [comment] 2018-03-02 16:20
Yea it does...
I'll post an image if i can. 
One install create TheHive
Another install creates thehive-3.0.6

**Comment by 3c7** [comment] 2018-03-02 16:41
Just tried in a docker container:
```
root@7899a25b7932:/tmp# wget http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
--2018-03-02 16:37:33--  http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
Resolving dl.bintray.com (dl.bintray.com)... 75.126.118.188
Connecting to dl.bintray.com (dl.bintray.com)|75.126.118.188|:80... connected.
HTTP request sent, awaiting response... 302
Location: http://akamai.bintray.com/12/121b45d0f9b8eaaf306b283b44a5b8c724ad74f0786444e790fadc84e4489703?__gda__=exp=1520009369~hmac=771e7fc020403f753fa46cf6e2ec1df0c4e9e2e6a218986406b4b78b6e664982&response-content-disposition=attachment%3Bfilename%3D%22TheHive_3.0.6-1_all.deb%22&response-content-type=application%2Fx-debian-package&requestInfo=U2FsdGVkX18xZ3TmGgfj9_5LhsX8cuqHlNcrjlq1sDI1mvXwsztxs0i0FMEmM3DZhvC_Ozedjrd_S4-HXUzwKjJ8u2sNLAKaGks-iZxhcIp3TR7Yoj1_UAkzq3scY2eP&response-X-Checksum-Sha1=d3d02314b947a3bc1316c4df8659b0936e5236fb&response-X-Checksum-Sha2=121b45d0f9b8eaaf306b283b44a5b8c724ad74f0786444e790fadc84e4489703 [following]
--2018-03-02 16:37:33--  http://akamai.bintray.com/12/121b45d0f9b8eaaf306b283b44a5b8c724ad74f0786444e790fadc84e4489703?__gda__=exp=1520009369~hmac=771e7fc020403f753fa46cf6e2ec1df0c4e9e2e6a218986406b4b78b6e664982&response-content-disposition=attachment%3Bfilename%3D%22TheHive_3.0.6-1_all.deb%22&response-content-type=application%2Fx-debian-package&requestInfo=U2FsdGVkX18xZ3TmGgfj9_5LhsX8cuqHlNcrjlq1sDI1mvXwsztxs0i0FMEmM3DZhvC_Ozedjrd_S4-HXUzwKjJ8u2sNLAKaGks-iZxhcIp3TR7Yoj1_UAkzq3scY2eP&response-X-Checksum-Sha1=d3d02314b947a3bc1316c4df8659b0936e5236fb&response-X-Checksum-Sha2=121b45d0f9b8eaaf306b283b44a5b8c724ad74f0786444e790fadc84e4489703
Resolving akamai.bintray.com (akamai.bintray.com)... 2.18.234.166
Connecting to akamai.bintray.com (akamai.bintray.com)|2.18.234.166|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 112336236 (107M) [application/x-debian-package]
Saving to: 'TheHive_3.0.6-1_all.deb'

TheHive_3.0.6-1_all.deb       100%[=================================================>] 107.13M  1.13MB/s    in 85s

2018-03-02 16:38:59 (1.26 MB/s) - 'TheHive_3.0.6-1_all.deb' saved [112336236/112336236]

root@7899a25b7932:/tmp# dpkg -i TheHive_3.0.6-1_all.deb
Selecting previously unselected package thehive.
(Reading database ... 5073 files and directories currently installed.)
Preparing to unpack TheHive_3.0.6-1_all.deb ...
Unpacking thehive (3.0.6-1) ...
dpkg: dependency problems prevent configuration of thehive:
 thehive depends on openjdk-8-jre-headless; however:
  Package openjdk-8-jre-headless is not installed.

dpkg: error processing package thehive (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (229-4ubuntu21) ...
Errors were encountered while processing:
 thehive
root@7899a25b7932:/tmp# apt install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  ca-certificates-java dbus fontconfig-config fonts-dejavu-core java-common krb5-locales libavahi-client3
  libavahi-common-data libavahi-common3 libcap-ng0 libcups2 libdbus-1-3 libexpat1 libffi6 libfontconfig1 libfreetype6
  libgmp10 libgnutls30 libgssapi-krb5-2 libhogweed4 libjpeg-turbo8 libjpeg8 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0 liblcms2-2 libnettle6 libnspr4 libnss3 libnss3-nssdb libp11-kit0 libpcsclite1 libpng12-0
  libsqlite3-0 libtasn1-6 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxi6 libxrender1 libxtst6
  openjdk-8-jre-headless ucf x11-common
Suggested packages:
  dbus-user-session | dbus-x11 default-jre cups-common gnutls-bin krb5-doc krb5-user liblcms2-utils pcscd libnss-mdns
  fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  ca-certificates-java dbus fontconfig-config fonts-dejavu-core java-common krb5-locales libavahi-client3
  libavahi-common-data libavahi-common3 libcap-ng0 libcups2 libdbus-1-3 libexpat1 libffi6 libfontconfig1 libfreetype6
  libgmp10 libgnutls30 libgssapi-krb5-2 libhogweed4 libjpeg-turbo8 libjpeg8 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0 liblcms2-2 libnettle6 libnspr4 libnss3 libnss3-nssdb libp11-kit0 libpcsclite1 libpng12-0
  libsqlite3-0 libtasn1-6 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxi6 libxrender1 libxtst6
  openjdk-8-jre-headless ucf x11-common
0 upgraded, 48 newly installed, 0 to remove and 21 not upgraded.
1 not fully installed or removed.
Need to get 33.9 MB of archives.
After this operation, 125 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libnspr4 amd64 2:4.13.1-0ubuntu0.16.04.1 [112 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libsqlite3-0 amd64 3.11.0-1ubuntu1 [396 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libnss3-nssdb all 2:3.28.4-0ubuntu0.16.04.3 [10.6 kB]
Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Adding debian:GeoTrust_Primary_Certification_Authority_-_G2.pem
Adding debian:Security_Communication_EV_RootCA1.pem
Adding debian:Certinomis_-_Autorité_Racine.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:Certplus_Class_2_Primary_CA.pem
Adding debian:Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem
Adding debian:Camerfirma_Chambers_of_Commerce_Root.pem
Adding debian:QuoVadis_Root_CA_2.pem
Adding debian:Certigna.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Adding debian:Comodo_Secure_Services_root.pem
Adding debian:Comodo_AAA_Services_root.pem
Adding debian:DigiCert_High_Assurance_EV_Root_CA.pem
Adding debian:Certum_Trusted_Network_CA.pem
Adding debian:Comodo_Trusted_Services_root.pem
Adding debian:thawte_Primary_Root_CA.pem
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:DST_ACES_CA_X6.pem
Adding debian:CFCA_EV_ROOT.pem
Adding debian:Security_Communication_RootCA2.pem
Adding debian:COMODO_ECC_Certification_Authority.pem
Adding debian:thawte_Primary_Root_CA_-_G2.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:ACCVRAIZ1.pem
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:SwissSign_Gold_CA_-_G2.pem
Adding debian:GlobalSign_Root_CA_-_R2.pem
Adding debian:Chambers_of_Commerce_Root_-_2008.pem
Adding debian:QuoVadis_Root_CA.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R5.pem
Adding debian:EE_Certification_Centre_Root_CA.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Adding debian:Starfield_Class_2_CA.pem
Adding debian:Actalis_Authentication_Root_CA.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:China_Internet_Network_Information_Center_EV_Certificates_Root.pem
Adding debian:VeriSign_Universal_Root_Certification_Authority.pem
Adding debian:Deutsche_Telekom_Root_CA_2.pem
Adding debian:LuxTrust_Global_Root_2.pem
Adding debian:Buypass_Class_2_Root_CA.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
done.
Setting up openjdk-8-jre-headless:amd64 (8u151-b12-0ubuntu0.16.04.2) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up thehive (3.0.6-1) ...
Creating system group: thehive
Creating system user: thehive in thehive with thehive daemon-user and shell /bin/false
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
root@7899a25b7932:/tmp# ls /opt/thehive/
README.md  bin  conf  lib  logs  migration
root@7899a25b7932:/tmp# ls /opt/thehive/bin
thehive
root@7899a25b7932:/tmp# ls /etc/thehive
application.conf  logback.xml
```
Nothing special there.

**Comment by jimbolya0607** [comment] 2018-03-02 17:23
Huh - ok -
I haven't had the chance to work on this since my last email.
Hopefully I'll be able to have a go at it tonight.  I had some time this
morning to work with it.

Jimbo

**Comment by jimbolya0607** [comment] 2018-03-03 02:59
Nils - would this command also work with cortex?

**Comment by jimbolya0607** [comment] 2018-03-03 03:23
By the way Nils, ran your commands - worked like a charm...

Thanks!!!

**Comment by 3c7** [comment] 2018-03-03 11:04
Great.

**Comment by 3c7** [comment] 2018-03-03 11:06
As the documentation is correct at this point and @To-om seems to be in contact with Bintray for solving this, I'll close this issue for now.
Related: https://github.com/TheHive-Project/TheHive/issues/500

**Closed by 3c7** 2018-03-03 11:06 UTC

**Comment by neomh** [comment] 2018-03-12 12:08
same error here: 

E: Failed to fetch https://dl.bintray.com/cert-bdf/debian/dists/any/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jimbolya0607** [comment] 2018-03-12 13:52
Here's the install that i used.  The bintray is off, and is being worked on
from what Understand.  I adjusted for Cortex as well.  Installed with no
issues.

Jimbo

sudo wget http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
sudo dpkg -i TheHive_3.0.6-1_all.deb
sudo apt install -f

**Comment by neomh** [comment] 2018-03-12 14:23
@jimbolya0607 

Tried this but getting this error : 
Oops, cannot start the server.
Configuration error: Configuration error[application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
	at play.api.Configuration$.configError(Configuration.scala:155)
	at play.api.Configuration$.load(Configuration.scala:101)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:113)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:49)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:978)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at play.api.Configuration$.$anonfun$load$5(Configuration.scala:73)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.Configuration$.load(Configuration.scala:69)
	... 5 more
Caused by: com.typesafe.config.ConfigException$IO: application.conf: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	... 12 more
Caused by: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	... 15 more


>  Here's the install that i used.  The bintray is off, and is being worked on
> from what Understand.  I adjusted for Cortex as well.  Installed with no
> issues.
> 
> Jimbo
> 
> sudo wget http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
> sudo dpkg -i TheHive_3.0.6-1_all.deb
> sudo apt install -f

**Comment by jimbolya0607** [comment] 2018-03-12 14:25
that's odd - it should install the java with the package.
are you installing it on a fresh machine or do you already have other apps
on the machine?

Jimbo

**Comment by neomh** [comment] 2018-03-12 14:26
> that's odd - it should install the java with the package.
> are you installing it on a fresh machine or do you already have other apps
> on the machine?
> 

It's a fresh VM ...
> Jimbo

**Comment by jimbolya0607** [comment] 2018-03-12 14:39
What OS?
I use Ubuntu 16.04 for just about everything...

**Comment by neomh** [comment] 2018-03-12 14:49
> What OS?
> I use Ubuntu 16.04 for just about everything..

Same here...

**Comment by jimbolya0607** [comment] 2018-03-12 14:53
What command are you using to start the server for the first time?

I use this one typically:

Change your current directory to TheHive installation directory
(/opt/thehive in this guide), then execute:

sudo bin/thehive -Dconfig.file=/etc/thehive/application.conf


Also did you run this?
The error your getting is a play issue so just curious...

sudo mkdir /etc/thehive

(cat << _EOF_
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the
same key!
play.http.secret.key="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64
| head -n 1)"
_EOF_
) | sudo tee -a /etc/thehive/application.conf


Jimbo

**Comment by jimbolya0607** [comment] 2018-03-12 14:54
Also - just found this.  Might be helpful:

https://github.com/spark-notebook/spark-notebook/issues/893

Jimbo

**Comment by 3c7** [comment] 2018-03-21 10:35
Just FYI: This should be solved now.

**Comment by neomh** [comment] 2018-03-22 14:28
> Just FYI: This should be solved now.

I will try again. Thank you

**Comment by jinverar** [comment] 2019-05-01 02:04
This work around no longer works. 

# wget http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
--2010-10-05 14:21:31--  http://dl.bintray.com/cert-bdf/debian/TheHive_3.0.6-1_all.deb
Resolving dl.bintray.com (dl.bintray.com)... 52.32.49.40, 54.218.43.24
Connecting to dl.bintray.com (dl.bintray.com)|52.32.49.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2010-10-05 14:21:31 ERROR 404: Not Found.

**Comment by jinverar** [comment] 2019-05-01 02:06
I may have found it here
https://bintray.com/thehive-project/debian-beta/download_file?file_path=thehive_3.3.0-1_all.deb

**Comment by jinverar** [comment] 2019-05-01 02:09
oops
https://bintray.com/thehive-project/debian-stable/download_file?file_path=pool%2Ft%2Fthehive%2FTheHive_3.0.10-1_all.deb

**Comment by jinverar** [comment] 2019-05-01 02:10
wget --no-check-certificate https://bintray.com/thehive-project/debian-stable/download_file?file_path=pool%2Ft%2Fthehive%2FTheHive_3.0.10-1_all.deb

**Comment by jinverar** [comment] 2019-05-02 00:24
https://bintray.com/thehive-project/debian-beta/thehive/3.3.0-RC6#files

**Comment by medd7517** [comment] 2023-09-06 16:29
I just tried to install thehive4 and i found the same result 
 sudo apt-get install thehive4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package thehive4
